name: ESLint Check

on:
  workflow_call:

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
       - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install Dependencies
      run: npm install
    - name: Run ESLint and Save Report
      if: always()
      run: |
        npx eslint src --ext .js,.jsx,.ts,.tsx -f html -o eslint-report.html
    - name: Upload ESLint Report
      uses: actions/upload-artifact@v4
      with:
        name: eslint-report
        path: eslint-report.html
