name: ESLint Check

on:
  workflow_call:

jobs:
  lint_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint
        run: |
            npm init -y
            npm install eslint@9 --save-dev

            # Create a valid eslint.config.js
            cat <<EOL > eslint.config.js
            export default [
                {
                    ignores: ["node_modules/"], 
                    rules: {
                    "semi": ["error", "always"],
                    "quotes": ["error", "double"],
                    "no-unused-vars": "warn",
                    "no-var": "error",
                    "arrow-spacing": ["error", { "before": true, "after": true }],
                    "object-curly-spacing": ["error", "always"],
                    "space-before-function-paren": ["error", "always"]
                    },
                },
                ];
            EOL

      - name: Run ESLint
        run: npx eslint *.js

  lighthouse_audit:
    needs: lint_code  
    uses: ./.github/workflows/lighthouse.yml
